version: '3.0'
services: 
  phantomjs:
    image: wernight/phantomjs
    restart: always
    command: phantomjs --webdriver=9222
  dota2mdi:
    build: .
    depends_on: 
      - phantomjs
    ports: 
      - "8080:8080"
    restart: always